version: 2.1
orbs:
    docker: circleci/docker@1.0.1
    kube-orb: circleci/kubernetes@0.11.0
    go: circleci/go@1.7.1
    helm: circleci/helm@3.1.0

executors:
  go_cimg:
    docker:
      - image: cimg/go:1.24
    resource_class: large

  local_cluster_test_executor:
    machine:
      image: ubuntu-2204:2022.10.2
    resource_class: large

commands:
  skopeo-install:
    description: Install Skopeo
    steps:
      - run:
          name: Apt Install Skopeo
          command: sudo apt-get update -y && sudo apt-get install -y skopeo
  kubectl-install:
    description: Install kubectl
    steps:
      - run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - run: sudo chmod +x kubectl
      - run: sudo mv kubectl /usr/local/bin
  kind-install:
    description: Install kind
    steps:
      - run: curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.24.0/kind-linux-amd64
      - run: chmod +x kind
      - run: sudo mv kind /usr/local/bin
      - run: curl -Lo cloudprovider.tgz https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/v0.6.0/cloud-provider-kind_0.6.0_linux_amd64.tar.gz
      - run: tar xzf cloudprovider.tgz
      - run: sudo mv cloud-provider-kind /usr/local/bin
  operator-sdk-install:
    description: Install operator-sdk
    steps:
      - run: curl -LO https://github.com/operator-framework/operator-sdk/releases/latest/download/operator-sdk_linux_amd64
      - run: sudo chmod +x operator-sdk_linux_amd64
      - run: sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk
  helm-install:
    description: Install Helm CLI
    steps:
      - run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  compile_go_program:
    description: Compile specified platform.
    parameters:
      platform:
        type: string
      goos:
        type: string
      goarch:
        type: string
      exesuffix:
        default: ""
        type: string
    steps:
      - run:
          name: Building << parameters.platform >>
          command: >-
            VERSION="${CIRCLE_TAG:-ci-${CIRCLE_BUILD_NUM}}";
            GOOS=<< parameters.goos >>
            GOARCH=<< parameters.goarch >>
            go build -ldflags "-X github.com/skupperproject/skupper/internal/version.Version=${VERSION}"
            -o dist/<< parameters.platform >>/skupper<< parameters.exesuffix >>
            ./cmd/skupper
      - run:
          name: Audit << parameters.platform >>
          command: >-
            sha512sum dist/<< parameters.platform >>/skupper<< parameters.exesuffix >>;
            file dist/<< parameters.platform >>/skupper<< parameters.exesuffix >>;
            go version -m dist/<< parameters.platform >>/skupper<< parameters.exesuffix >>;

yaml-templates:
  branch_filters: &run_for_all_branches
    filters:
      tags:
        ignore: /.*/

  v2_branch_filters: &run_for_v2_branch
    filters:
      branches:
        ignore: /.*/
        only: /main/

  release_filters: &run_for_numeric_tags
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /[0-9].*/

  v2_release_requires: &v2_release_requires
    requires:
      - build-all
      - test-skupper-binary
      - test
      - build-oci-images

workflows:
  version: 2.1
  build:
    jobs:
      - generate-network-observer-operator-bundle:
          <<: *run_for_all_branches

jobs:
  generate-network-observer-operator-bundle:
    executor:
      name: local_cluster_test_executor
    steps:
      - docker/install-docker
      - skopeo-install
      - checkout
      - go/mod-download-cached
      - kubectl-install
      - operator-sdk-install
      - run:
          name: Clone the skupper report
          command: |
            git clone https://github.com/skupperproject/skupper.git ~/skupper
      - run: |
          cd ~/skupper
          make generate-network-observer-operator-bundle
      - persist_to_workspace:
          root: .
          paths:
            - network-observer-operator
